server {
    listen 80;
    server_name helpdesk.example.nl;
    root /var/www/ticket-systeem/public;
    index index.php;

    client_max_body_size 12m;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }

    location ~ /\.(env|git|installed) {
        deny all;
    }
}
